
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_management
    username: root
    password: root
  
  
  data:
    rest:
      basePath: /restapi/v1/
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
    
logging:
  level:
    org:
      springframework:
        security: TRACE


        
         